# Generated by Django 2.1.2 on 2018-10-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='londonmetalexchange',
            name='id',
        ),
        migrations.AlterField(
            model_name='londonmetalexchange',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
