# Generated by Django 2.1.2 on 2018-10-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeserie',
            old_name='serie',
            new_name='name',
        ),
    ]
