# Generated by Django 2.1.2 on 2018-10-25 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181024_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='timeserie',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TimeSerie'),
        ),
    ]
