# Generated by Django 2.1.2 on 2018-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181024_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='LondonMetalExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cobre', models.DecimalField(decimal_places=2, max_digits=20)),
                ('zinco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('aluminio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chumbo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estanho', models.DecimalField(decimal_places=2, max_digits=20)),
                ('niquel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dolar', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
